### ISSUE TITLE
Set up project base code

### ISSUE THREAD

**Issue by DevArenaCN** [SE17GroupH/Zap#1]
Adding project base code and push it to GitHub

**Comment by KaustubhG** [comment]
@DevArenaCN  I am not able to push the project. It says permission denied. Could you give me access rights.

**Comment by DevArenaCN** [comment]
I have give you permission. Check your invitation.

**Comment by KaustubhG** [comment]
Got it, thanks! :)

I have pushed a basic hello world app. It should give us a working code base to build our application.
