### ISSUE TITLE
Work out program flow for the app

### ISSUE THREAD

**Issue by DevArenaCN** [SE17GroupH/Zap#14]

**Comment by KaustubhG** [comment]
will do that tonight most probably.

**Comment by DevArenaCN** [comment]
Yeah we need to figure this out before we move forward. I'm drafting one right now and will keep you guys posted here

**Comment by KaustubhG** [comment]
sure

**Comment by DevArenaCN** [comment]
![untitled diagram](https://cloud.githubusercontent.com/assets/4381690/22766657/c79ed422-ee44-11e6-920e-ff6dee594886.png)

Here's a basic program flow for the Android app. Let me know what you guys think
