### ISSUE TITLE
Creating all pages in the app

### ISSUE THREAD

**Issue by DevArenaCN** [SE17GroupH/Zap#16]
Creating pages shown in the program flow as showed here. Modification can be made by your choice, but I would like to discuss it in this issue first. Thanks!

**Comment by DevArenaCN** [comment]
Repeat...close this issue

**Comment by KaustubhG** [comment]
done.

**Comment by KaustubhG** [comment]
done.

**Comment by DevArenaCN** [comment]
Have you done a pull request to merge your code to the master branch?

**Comment by KaustubhG** [comment]
Yeah.
I have mentioned you and sid in the comment for the pull request.

**Comment by DevArenaCN** [comment]
Saw it. Looks good, great work. I would say merge the code first then close the issue next time.

**Comment by thegreyd** [comment]
I only see one activity which is activiy_hello_world.xml. Do i have to switch to Kaustubh branch?

**Comment by DevArenaCN** [comment]
@thegreyd Yes you need to switch to his branch to check the code

**Comment by thegreyd** [comment]
cool.

**Comment by thegreyd** [comment]
The gradle system messes things up pretty quickly. Even if I open the project to view in master or other branch it modifies some files :sweat_smile: Have to be careful.

**Comment by thegreyd** [comment]
So if I want to modify KG's codem, I would create my branch, and then merge his branch with mine, and then proceed to commit changes there, right?

**Comment by thegreyd** [comment]
@DevArenaCN How do I work on KG's code in my branch?

**Comment by DevArenaCN** [comment]
If things works fine, I'll confirm the pull request, which will makes KG's code to the master branch. Then on your local machine, what you need to do is either switch to master branch, run a  `git pull` command, then switch back to your branch, and do a `git merge master` command; Or you can do just on your own branch (locally), run a `git merge origin master` command, it will just merge the latest code from the master branch with your branch (locally). After that what I normally do is checking all the functionalities, if all goes well, commit all the files and push it to my branch on github

**Comment by thegreyd** [comment]
Or if I switch to KG's branch and then create a new branch, that would have the base of KG's code ? And then modify it. Basically I can have 2 branches, 1 of KG's code and one with master. Would that work?

**Comment by DevArenaCN** [comment]
Now if you do a `git pull` from the master branch, you should have the latest code

**Comment by DevArenaCN** [comment]
@thegreyd The best way would be switch to master branch, do `git pull`, and then switch back to your branch and do `git merge master`
