### ISSUE TITLE
Fingerprint authentication inside the app

### ISSUE THREAD

**Issue by DevArenaCN** [SE17GroupH/Zap#17]
Adding fingerprint authentication function inside the app

**Comment by thegreyd** [comment]
There is a working prototype now of local fingerprint authentication. I'll push and create a pull request soon.

**Comment by thegreyd** [comment]
Guide used was this. Posting here for reference.
http://www.androidauthority.com/how-to-add-fingerprint-authentication-to-your-android-app-747304/

**Comment by DevArenaCN** [comment]
Is this finished? @thegreyd Let me know if I can close this issue
