### ISSUE TITLE
Adding register function

### ISSUE THREAD

**Issue by DevArenaCN** [SE17GroupH/Zap#18]
Adding register function to the app, need communication between server and app.

Harold-- Server side API calls creation.

Sid-- Android app side

**Comment by thegreyd** [comment]
@DevArenaCN So I am not entirely sure how this would be implemented. In what form will the data from the Android app be sent to the server? Will it be an api call? Will the server return some token? I

**Comment by thegreyd** [comment]
This is something I was reading. Authentication using http request: https://stackoverflow.com/questions/1968416/how-to-do-http-authentication-in-android

**Comment by DevArenaCN** [comment]
Yes. It will be some kind of form that you post to the server ( which I will give you the documentation once I'm finished) , you will get a JSON back so that you can parse and do things accordingly in the app.

**Comment by DevArenaCN** [comment]
It will be something like this: http://lucatironi.net/tutorial/2012/10/15/ruby_rails_android_app_authentication_devise_tutorial_part_one/

**Comment by DevArenaCN** [comment]
Done with the server side.

**Comment by thegreyd** [comment]
Registration now works in the Android app. Some refinements needed, will open relevant issues.
