### ISSUE TITLE
New Repo for server stuff

### ISSUE THREAD

**Issue by KaustubhG** [SE17GroupH/Zap#21]
@DevArenaCN @thegreyd 
Guys could you create a new repo for the server-side code?
Putting everything in the same repo will create a mess.

**Comment by DevArenaCN** [comment]
My thought would be putting them in different ones would create issues with the GutHub issue section where we need to cross communication with different repos. Is there some kind of issue with your project? I

**Comment by KaustubhG** [comment]
I havent checked it out yet but the studio could mess things up while running and building the apk for the app.

Plus for the common issues stuff: we can create a project for the SETeamH organisation as a whole which will give access to all the issues across all repos contained in an org.

**Comment by KaustubhG** [comment]
I have created a new project for the whole org. It resolves the cross-communication issue :)

**Comment by DevArenaCN** [comment]
Alright. I'm moving the files before class.

**Comment by KaustubhG** [comment]
Sure. Thanks! :)

**Comment by thegreyd** [comment]
We have our server hosted in our ideas repo. We could continue to use that maybe?

**Comment by DevArenaCN** [comment]
It has been moved to the new repo. Closing this issue
