### ISSUE TITLE
Voice-DNA : get familiar with API and create a toy working app.

### ISSUE THREAD

**Issue by KaustubhG** [SE17GroupH/Zap#23]
- [x] Familiarize with Microsoft  API
- [x] Make a toy app recording and saving voice
- [x] Incorporate functionality in Zap

**Comment by DevArenaCN** [comment]
Found another library that we could use. Cost a bit but hopefully we can use this.
https://siv.voiceprintportal.com/apidocs.jsp

**Comment by DevArenaCN** [comment]
https://github.com/voiceittech/VoiceIt-Android-Wrapper-BETA   Api for Android can be found here.

**Comment by KaustubhG** [comment]
Me and sid were working together this afternoon on the voice-dna stuff.
Voice Recording is now working inside the app. 
Sid is working on making API requests for voice-dna enrollment and verification.

We have decided the app flow for Voice as follows:

HomePage ---> Login ----> Login via Voice-DNA

```
if(user isn't registered by voice){
 show the user enrollment screen (the screen where we record 3 voice samples and enroll the user)
}  
else{
 show the user verification screen. (the screen where we only record 1 voice sample for verification)
}
```

**Comment by DevArenaCN** [comment]
Noted. Great work @KaustubhG @thegreyd

**Comment by KaustubhG** [comment]
Done.
