### ISSUE TITLE
Status update

### ISSUE THREAD

**Issue by DevArenaCN** [SE17GroupH/Zap#24]
So, as you guys know, the register, login and logout function has already been done, and I think I have a pretty solid idea on how to implement the magiclink stuff. Any update on your end? Should we meet up earlier before class to discuss some issues you guys are facing? @thegreyd @KaustubhG

**Comment by KaustubhG** [comment]
Hey guys
still stuck on the API calls. :(
I guess I could change tracks and get the authentication thing done now that the server up...

**Comment by thegreyd** [comment]
I am able to use the Zap server api to login, it returns a json file with auth token. Have a working version, some more work needed.

**Comment by KaustubhG** [comment]
I have got the linking of a url to our app done.

**Comment by DevArenaCN** [comment]
@KaustubhG Great work! I'm almost finished with the emailing part, probably gonna finish the api calls before tomorrow's lecture. Can we still meet up 30 min before to have a quick meeting? I need some pointers on that url call. @thegreyd

**Comment by KaustubhG** [comment]
Sure

**Comment by DevArenaCN** [comment]
Quick update: email can be successfully sent out along with the auth_token, now is just how we pass that back to the app, and do the authorization call to the server.

**Comment by thegreyd** [comment]
@DevArenaCN Is it a clickable link ? We'll need to open that link in the app right?

**Comment by DevArenaCN** [comment]
Hey guys, the API calls for magic link and verify if user's auth_token is valid has been created and tested, documentations can be found in [here](https://github.com/SE17GroupH/ZapServer/blob/master/README.md) Let me know if you guys have any problems using these.

**Comment by thegreyd** [comment]
@DevArenaCN I'm thinking of removing some login and logout api calls to Zapserver, because they seem unnecessary. This way the communication to server will happen in one way, through the email password login. If that's successfully validated through the server then we store it in the app to locally authenticate. Won't be making login api calls to Zapserver on fingerprint and voice auth, because we require login through email-password first.

**Comment by DevArenaCN** [comment]
Yes I guess that would be fine for demo purposes, but in the real case it would need to talk with the server for authentication. One thing you could do is after login with username and password, store the auth-token, and just do the verification of the token instead for the other two login method.

**Comment by thegreyd** [comment]
Yes I am storing the username password and auth token. How do you verify the auth token?

**Comment by DevArenaCN** [comment]
Still it's gonna be an API call to the server, there no way around that, and honestly I don't think we should either.

**Comment by KaustubhG** [comment]
@thegreyd  could you mail me the SubKey.java file?

**Comment by DevArenaCN** [comment]
Link format for register confirmation: http://zapserver.herokuapp.com/users/confirmation?confirmation_token=vxgUvAm1SG5bQWyzQDfF

**Comment by thegreyd** [comment]
Done
