### ISSUE TITLE
Error on wrong credentials

### ISSUE THREAD

**Issue by thegreyd** [SE17GroupH/Zap#26]
Getting exception when user enters wrong username or password:

`java.io.FileNotFoundException: https://zapserver.herokuapp.com/api/sessions`

**Comment by DevArenaCN** [comment]
`$ curl -k -v -H "Content-Type:application/json" -X POST -d '{"session":{"password":"12345677","email":"example@zapserver.com"}}' https://zapserver.herokuapp.com/api/sessions/`
`Note: Unnecessary use of -X or --request, POST is already inferred.`
`*   Trying 184.73.212.255...`
`* TCP_NODELAY set`
`* Connected to zapserver.herokuapp.com (184.73.212.255) port 443 (#0)`
`* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256`
`* Server certificate: *.herokuapp.com`
`* Server certificate: DigiCert SHA2 High Assurance Server CA`
`* Server certificate: DigiCert High Assurance EV Root CA`
`> POST /api/sessions/ HTTP/1.1`
`> Host: zapserver.herokuapp.com`
`> User-Agent: curl/7.51.0`
`> Accept: */*`
`> Content-Type:application/json`
`> Content-Length: 67`
`> `
`* upload completely sent off: 67 out of 67 bytes`
`< HTTP/1.1 422 Unprocessable Entity`
`< Server: Cowboy`
`< Date: Tue, 14 Feb 2017 21:52:13 GMT`
`< Connection: keep-alive`
`< X-Frame-Options: SAMEORIGIN`
`< X-Xss-Protection: 1; mode=block`
`< X-Content-Type-Options: nosniff`
`< Content-Type: application/json; charset=utf-8`
`< Cache-Control: no-cache`
`< X-Request-Id: ec10c234-6305-4daa-aef6-d87ac70ad64a`
`< X-Runtime: 0.807859`
`< Transfer-Encoding: chunked`
`< Via: 1.1 vegur`
`< `
`* Curl_http_done: called premature == 0`
`* Connection #0 to host zapserver.herokuapp.com left intact`
`{"errors":"Invalid email or password"}`


I did a cURL and this is the JSON that should be returned (Last line)

**Comment by thegreyd** [comment]
On wrong credentials I am getting a HTTP error code, which when the urlconnection object in the app receives it kinda shuts off on its own, and doesn't show any returned message. This is fine, based on the return code we could segregate. 

These are the codes that are received
- On correct username, wrong password: 422
- On wrong username: 500
- On correct username and password: 200

**Comment by thegreyd** [comment]
If the response code is other than error, like 200, I could possibly get the json file. But we could decide what way would be the best.

**Comment by thegreyd** [comment]
Registration works now. But I don't get any json in return, only codes.
- Email already in use - 422
- invalid email/short password - 422
- Correct email and password - 201

**Comment by thegreyd** [comment]
The standard library functions for this are buggy/unreliable. Found a really nice library OkHttp, switching to that for API calls. Much cleaner interface and getting the correct json response now. Issue resolved.
