### ISSUE TITLE
Registration process flow

### ISSUE THREAD

**Issue by thegreyd** [SE17GroupH/Zap#27]
We've to decide how the registration will take place. Currently we are taking email, password as input.
- Add authentication mode as input - magic link/fingerprint. to store which user has registered for magic link. 
- Verify email address? - for magic link to work we need a verified email address. 
- For fingerprint the server doesn't have to do anything, so no case there.
- I can do the validation of password, in the app itself, at least 6 chars.
- After registration
    - do we redirect to the login page
    - or login automatically ? 
    - it will depend if user can immediately login after registering.

**Comment by thegreyd** [comment]
I tested a few things:
- When you register you get an auth token, so we can login directly.
- If we don't we can redirect to login page. User can login immediately after registration

**Comment by thegreyd** [comment]
After discussion this is what we're doing:

- [x] No choosing of authentication mode. By default user can use fingerprint, magic link, voice/face/
- [x] In magic link, first verify the email address
- [ ] In fingerprint, first store the username and password. Then afterwards, when the username+fingerprint is authenticated, send the stored password
- [x] Do some validation on password, at least 6 chars. Username contains "@".
- [x] After registration redirect to login page.

**Comment by DevArenaCN** [comment]
email confirmation has been implemented.

**Comment by DevArenaCN** [comment]
@thegreyd I have clear the whole database so you have to re-sign up for testing. Sorry about the inconvenience.

**Comment by thegreyd** [comment]
@DevArenaCN Not a problem. The only thing left on the server side I can think of, is resetting password. Do you think we should do it, or leave it for later.

**Comment by DevArenaCN** [comment]
Resetting the password I believe has already in the server side, but I haven't release the API for it. We can finish the major parts and then work on those small details.

**Comment by thegreyd** [comment]
Oh that's great.

**Comment by DevArenaCN** [comment]
I think the program flow is done. Closing this issue
