### ISSUE TITLE
Make the App UI prettier

### ISSUE THREAD

**Issue by thegreyd** [SE17GroupH/Zap#37]
Currently have a pretty barebones UI. Make it prettier.

**Comment by thegreyd** [comment]
Disable the buttons when pressing them doesn't lead to anything. Currently in the app a error toast notification is displayed which is not ideal.

**Comment by thegreyd** [comment]
- https://codelabs.developers.google.com/codelabs/material-design-style/index.html?index=..%2F..%2Findex#0

**Comment by KaustubhG** [comment]
UI looks pretty decent now! 😄
