### ISSUE TITLE
Separate heavy operations from UI

### ISSUE THREAD

**Issue by thegreyd** [SE17GroupH/Zap#47]
Currently all the processing is done when a button is pressed, which leads to hang the app, and skip frames. Sometimes you are not logged in from the heavy login activity due to the skipped frame. This also affects voice login operations. 

Potential solutions:
- https://developer.android.com/reference/android/os/AsyncTask.html  
- https://stackoverflow.com/questions/14678593/the-application-may-be-doing-too-much-work-on-its-main-thread#21126690

Todo:

- [x] Login api call 
- [x] Magic link api call
- [x] Register api call
- [x] Voice enroll api call
- [x] Voice verify api call

**Comment by KaustubhG** [comment]
Will look into this one

**Comment by thegreyd** [comment]
Done.
