### ISSUE TITLE
MagicLink issues

### ISSUE THREAD

**Issue by DevArenaCN** [SE17GroupH/Zap#5]

**Comment by KaustubhG** [comment]
@DevArenaCN  @thegreyd 
http://zapserver.herokuapp.com/magiclinks/auth_token=<auth_token>

**Comment by DevArenaCN** [comment]
@KaustubhG I've made some changes to the link above. That's the actual one we're using now

**Comment by KaustubhG** [comment]
Okay. I'll make the changes. 👍

**Comment by KaustubhG** [comment]
Integrated the magic link authentication. Getting errors executing the post call though 😕 
Will look into it tomorrow.

**Comment by KaustubhG** [comment]
Fixed the 'network on main thread' exception.
Now making the magic-link API call in a background thread.

**Comment by DevArenaCN** [comment]
UI has been modified for magic link email.
