### ISSUE TITLE
Fingerprint App crash

### ISSUE THREAD

**Issue by thegreyd** [SE17GroupH/Zap#50]
These are some conditions when the app crashes:
- [ ]  When fingerprint hardware is not present and fingerprint auth is opened.
- [x] When the storage and/or audio record permission are not given at voice auth.

**Comment by KaustubhG** [comment]
I'll take up this one today

**Comment by KaustubhG** [comment]
crash for denying permissions due to voice auth is fixed.

**Comment by DevArenaCN** [comment]
Is there an update on this?

**Comment by thegreyd** [comment]
Still unresolved.

**Comment by thegreyd** [comment]
Future improvement
