### ISSUE TITLE
VoiceDNA issues

### ISSUE THREAD

**Issue by DevArenaCN** [SE17GroupH/Zap#6]

**Comment by thegreyd** [comment]
Microsoft Voice api : https://westus.dev.cognitive.microsoft.com/docs/services/563309b6778daf02acc0a508/operations/56406930e597ed20c8d8549c

**Comment by thegreyd** [comment]
- apis
	- get all verification phrases
	- create profile
	- create enrollment
	- delete profile
	- get all profiles
	- get profile
	- reset enrollments
	- verification

- Procedure:
	- create verification profile id - using subscription id
		- using that profile id create enrollment - 3 api calls with 3 voice samples
	- call the verification api - using profile id and voice sample

**Comment by thegreyd** [comment]
The audio file format must meet the following requirements.
Container 	WAV
Encoding 	PCM
Rate 	16K
Sample Format 	16 bit
Channels 	Mono

**Comment by thegreyd** [comment]
Next step is to find android library and code to record audio and convert it into wav format specified above. Android doesn't natively suppory wav. I tried using this library: https://github.com/adrielcafe/AndroidAudioRecorder. But keep getting errors.

**Comment by thegreyd** [comment]
A better approach would be to first test the api (with some python code), and see if it works here (since its mentioned availability is only west-US), and then code up the application.

**Comment by thegreyd** [comment]
API works. Tested with Python scripts [here](https://github.com/Microsoft/Cognitive-SpeakerRecognition-Python).

**Comment by KaustubhG** [comment]
Voice Recorder Works! :dancing_men:

**Comment by thegreyd** [comment]
Lots of voice recognition functionality implemented today! Good job @KaustubhG :smile:

**Comment by thegreyd** [comment]
Core functionality is done now. Todo: Add proper instructions for enrollment.

**Comment by DevArenaCN** [comment]
Is there any issues regarding the voice recognition right now?

**Comment by thegreyd** [comment]
Done. We can open specific issues to deal with them.
