### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by KaustubhG** [SE17GroupH/Zap#61]

**Comment by thegreyd** [comment]
Testing methods and frameworks:
- JUnit
- Robolectric (unit and intergration tests)
- Espresso (functional tests)
- Mockito
- https://codelabs.developers.google.com/codelabs/android-testing/index.html?index=..%2F..%2Findex#0

**Comment by thegreyd** [comment]
So I was playing with gradle and JUnit. Thankfully lot of things are set up in Android Studio, to help test. JUnit and Espresso are included as dependencies. There are 2 types of tests - one which is not android specific - test, and one which requires android specific functions - androidTest.
- **test** , which are **unit tests** written with JUnit -  [go here in this folder](https://github.com/SE17GroupH/Zap/blob/master/app/src/test/java/teamh/zapapp/ExampleUnitTest.java).
- **androidTest**, which are **instrumentation tests** written with Espresso or other - [go here](https://github.com/SE17GroupH/Zap/tree/master/app/src/androidTest/java/teamh/zapapp)

References:
- https://developer.android.com/studio/test/index.html

**Comment by thegreyd** [comment]
- UI testing with Espresso: https://www.youtube.com/watch?v=W8LJjfkTKik&list=PLWz5rJ2EKKc-6HWg_jyP0U1zrVLHn65b2
- code snippet used: https://qathread.blogspot.com/2014/09/discovering-espresso-for-android-how-to.html
- okhttp mockwebserver: https://github.com/square/okhttp/tree/master/mockwebserver
- espresso testing: https://developer.android.com/training/testing/ui-testing/espresso-testing.html

**Comment by KaustubhG** [comment]
Me and @thegreyd  wrote some tests today.
We wrote unit-tests for checking correctness of functions
and end-to-end tests for checking end-to-end system functionality.

**Comment by DevArenaCN** [comment]
Great work guys! I'm seeing a lot of commits today. For server side there're test cases in place already so I think all I need to do is setting up TravisCI for it. I'll start on Thursday.

**Comment by thegreyd** [comment]
Started. For remaining open specific issues.
