### ISSUE TITLE
Intergrating with travisCI

### ISSUE THREAD

**Issue by thegreyd** [SE17GroupH/Zap#65]
travisCI is a build automation tool, and free to use with a public repo. It would be pretty cool if we got the tests automated with every commit. 

Resources:
- https://travis-ci.org
- https://travis-ci.org/getting_started
- https://docs.travis-ci.com/user/getting-started/

**Comment by thegreyd** [comment]
@DevArenaCN @KaustubhG You would have received a mail to grant authorization to travisCI for the organization repo. That's needed to integrate with travis.

**Comment by DevArenaCN** [comment]
I have authorized it a few mins ago. I'm gonna try to do that for the server side as well.

**Comment by thegreyd** [comment]
@DevArenaCN I require admin rights for the organization or this repo, to enable the integration. Can you grant me that

**Comment by DevArenaCN** [comment]
I thought I already did. I'll double check in a few mins.

**Comment by KaustubhG** [comment]
@thegreyd  I didn't receive a mail for granting authorization to travis CI...

**Comment by thegreyd** [comment]
@DevArenaCN I think in collaborators there are 2 kinds of access - write and admin. I have write access but for this I require admin access.

**Comment by thegreyd** [comment]
@KaustubhG Hmm maybe only the person with admin rights to the org repo gets it.

**Comment by DevArenaCN** [comment]
Ah, gotcha. I'll do that, almost home, don't have access to a laptop and can't seem to be done on my phone.

**Comment by KaustubhG** [comment]
I'll get started on travis CI by tonight 😄

**Comment by DevArenaCN** [comment]
Done. Sorry about the delay

**Comment by thegreyd** [comment]
So our first build is passing. Took a long time to get it right. Basically had to disable instrumentation tests on travis (requires installing and running android device manager, which is a pain). Next to do is to securely get api keys to the build which are now stored in SubKey.java. In future the api keys will be stored in environment variables, and passed encrypted to travis.
