### ISSUE TITLE
No Internet Connection App Crash

### ISSUE THREAD

**Issue by thegreyd** [SE17GroupH/Zap#85]
When Internet connection is faulty, app crashes. This is handled at time of username/password login, but not handled at:
- Registration
- Magic link
- Confirmation link
- Voice enrollment
- Voice verification

**Comment by DevArenaCN** [comment]
Any updates?

**Comment by thegreyd** [comment]
Not done. Looking into it.

**Comment by thegreyd** [comment]
Future improvement
