### ISSUE TITLE
User eval

### ISSUE THREAD

**Issue by DevArenaCN** [SE17GroupH/Zap#87]
We need to have a meeting to discuss how we want to conduct the user evaluation. Let me know what you guys think

**Comment by thegreyd** [comment]
Yes, Let's put a signup sheet for that. When are you guys free next week. We should discuss the work needed for user eval, server and app. 

For the app i think, we need to prepare instructions to tell the user what to do. App icon and logo would be good.

For the server side, integrating microsoft api call for profile creation at account creation. This will make the voice login process very convenient for the end user. 

Apart from these I don't think we need more. We could implement timing in the app, that would depend on how easy it is, and what kind of statistics we record.

**Comment by KaustubhG** [comment]
We can start discussing over the weekend via comments and meetup next week maybe Tuesday.
How about that?

**Comment by DevArenaCN** [comment]
@thegreyd I'll add the Microsoft cognitiveId in the registration form and I'll write another API for getting that info, that will be done before Thursday. In the meantime, if @thegreyd and @KaustubhG could look into implementing some timing module inside the app for user registration and user login process that would be awesome.

**Comment by KaustubhG** [comment]
Sure, w'll work on that

**Comment by thegreyd** [comment]
Done
